### PR TITLE
Add stack metadata

### PR DESCRIPTION
**Pull request by chreekat**
Enables building the library with stack.

### CODE REVIEW

**Comment by myfreeweb** [comment]
Looks like I'll have to try stack...

**Comment by chreekat** [comment]
Yeah, for the most part you should be able to replace 'cabal' with 'stack' in your Makefile and everything will keep working! The exception is repl, which will become 'stack ghci'. There's also different artifact directories, naturally.

**Comment by myfreeweb** [comment]
Wait, isn't the point that I should replace *the makefile itself* with stack?

**Comment by chreekat** [comment]
No, stack is just an alternative to cabal-install. Your makefile does
useful things beyond the scope of both those tools, like running hpc,
cleaning up .cabal-sandbox (.stack-work in stack's case), passing -fno-hpc
to the repl, and so on.

**Pull request merged**
